# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

python:
  pre_install:
    - pip install numpy
  install:
    - requirements: docs/requirements.txt
